version: '2'
services:
  batch:
    image: maven:3.3.9-jdk-8
    volumes:
     - /etc/localtime:/etc/localtime
     - ${HOME}/glytoucan/maven:/root/.m2
     - ${WORKSPACE_PARENT}/${WORKSPACE}/${PROJECT}:/workspace
    working_dir: /workspace/
    command: mvn -DskipTests=true clean package
    restart: never
    environment:
     - SPRING_TRIPLESTORE_PASSWORD
     - SPRING_TRIPLESTORE_URL
